service: aws-starwars-serverless-api
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "3"

custom:
  autoswagger:
    title: 'Trips API'
    typefiles:
      - './src/types/vehicle.type.ts'
      - './src/types/errors.type.ts'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
          Resource:
            - { "Fn::GetAtt": ["VehiclesTable", "Arn"] }

functions:
  listVehicles:
    handler: src/handlers.listVehicles
    events:
      - httpApi:
          path: /vehicle
          method: get
          swaggerTags: ["Vehicles"]
          responses:
            200:
              description: "Successful API response"
              bodyType: "VehicleSpanishList"

  createVehicle:
    handler: src/handlers.createVehicle
    events:
      - httpApi:
          path: /vehicle
          method: post
          swaggerTags: ["Vehicles"]
          consumes: [ 'application/json' ]
          produces: [ 'application/json' ]
          bodyType: "CreateVehicleDto"
          responses:
            201:
              description: "Vehicle was created successfully"
              bodyType: "VehicleSpanishDb"
            400:
              description: "Bad request"
              bodyType: "ErrorResponse"

plugins:
  - serverless-auto-swagger
  - serverless-plugin-typescript

resources:
  Resources:
    VehiclesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: VehiclesTable
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
